name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

    pull_request:
      branches:
        - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        action: actions/setup-node@v3
        with:
          node-version: 22
        run: npm run test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        if: github.ref == 'refs/head/main'
        env:
          CI: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
